# SPDX-FileCopyrightText: 2023 Colin-Tel <113523727+Colin-Tel@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers <thebluewulf@gmail.com>
# SPDX-FileCopyrightText: 2024 Adrian16199 <144424013+Adrian16199@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT <77995199+DEATHB4DEFEAT@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Fansana <fansana95@googlemail.com>
# SPDX-FileCopyrightText: 2024 FoxxoTrystan <45297731+FoxxoTrystan@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 FoxxoTrystan <trystan.garnierhein@gmail.com>
# SPDX-FileCopyrightText: 2024 Rane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 ShatteredSwords <135023515+ShatteredSwords@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Rosycup <178287475+Rosycup@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 SixplyDev <einlichen@gmail.com>
# SPDX-FileCopyrightText: 2025 Skubman <ba.fallaria@gmail.com>
# SPDX-FileCopyrightText: 2025 Timfa <timfalken@hotmail.com>
# SPDX-FileCopyrightText: 2025 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <flyingkarii@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: ForensicMantis
  name: job-name-mantis
  description: job-description-mantis
  playTimeTracker: JobForensicMantis
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 18000
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 3600
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - IPC
        - !type:CharacterTraitRequirement
          traits:
            - AnomalousPositronics
        - !type:CharacterTraitRequirement
          inverted: true
          traits:
            - ShadowkinBlackeye
  startingGear: ForensicMantisGear
  icon: "JobIconForensicMantis"
  supervisors: job-supervisors-rd
  canBeAntag: true # DeltaV - Mantis is no longer a Detective
  # whitelistRequired: true
  access:
  - Research
  - Maintenance
  - Mantis # DeltaV - Mantis, see Resources/Prototypes/_DV/Access/epistemics.yml
  special:
  - !type:AddComponentSpecial
    components:
    - type: Psionic
      powerSlots: 1 # TheDen - This only means that they don't start generating glimmer until they gain a second slot-taking power (they have room for one so all psionic jobs aren't just glimmer machines, and none of their innate powers take slots)
    - type: InnatePsionicPowers
      powersToAdd: # TheDen - They have no innate slot-taking powers, so they need 100 Potentia to gain a new power
        - MetapsionicPower # Doesn't take a power slot
        - TelepathyPower # Doesn't take a power slot
        - PsychognomyPower # TheDen - Doesn't take a power slot (and the psychic monitor should get a little extra information for roleplay)
        - AssayPower # Doesn't take a power slot

- type: startingGear
  id: ForensicMantisGear
  subGear:
  - ForensicMantisPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMantisDark # TheDen
    back: ClothingBackpackMantisFilled
    shoes: ClothingShoesSandalsMantisDark # TheDen
    head: ClothingHeadHoodMantisDark # TheDen
    id: ForensicMantisPDA
    # eyes: ClothingEyesGlassesSunglasses # TheDen
    ears: ClothingHeadsetMantis # TheDen
    gloves: ClothingHandsGlovesMantisDark # TheDen
    outerClothing: ClothingOuterCoatMantisAiry # TheDen
    belt: ClothingBeltMantisDark # TheDen
    # pocket1: BookPsionicsGuidebook # TheDen - Throwing this in their locker
    pocket1: BaseHandheldPsionicsRegistry # TheDen
  innerClothingSkirt: ClothingUniformJumpsuitMantisDark # TheDen - Not a jumpskirt, don't care, all options are robelike anyway
  satchel: ClothingBackpackSatchelMantisFilled
  duffelbag: ClothingBackpackDuffelMantisFilled

- type: startingGear
  id: ForensicMantisPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMantis
    head: ClothingHeadEnvirohelmMantis
    gloves: ClothingHandsGlovesEnviroglovesWhite
